name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11]  # List of Python versions to test against

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m venv venv                # Create virtual environment
        source ./venv/bin/activate          # Activate virtual environment
        pip install -r requirements.txt     # Install dependencies
        pip install pytest                  # Install pytest
        
    - name: Run tests
      run: |
        source ./venv/bin/activate          # Activate the virtual environment again before running tests
        pytest                              # Run tests
